{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import csv\n",
    "import calendar\n",
    "import plotly.graph_objs as go\n",
    "import plotly.express as px\n",
    "from plotly.subplots import make_subplots\n",
    "\n",
    "\n",
    "\n",
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import datetime as dt\n",
    "\n",
    "import os,sys,inspect\n",
    "from dash.dependencies import Input, Output, State\n",
    "\n",
    "current_dir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))\n",
    "#parent_dir = os.paths.dirname(current_dir)\n",
    "sys.path.insert(0, current_dir) \n",
    "from environmentVariables import environment_variables"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "user_key=environment_variables['mahaveer']\n",
    "pd.set_option('display.precision', 12)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      "Dash is running on http://127.0.0.1:8050/\n",
      "\n",
      " * Serving Flask app \"__main__\" (lazy loading)\n",
      " * Environment: production\n",
      "   WARNING: This is a development server. Do not use it in a production deployment.\n",
      "   Use a production WSGI server instead.\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:25] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:25] \"\u001b[37mGET /_dash-layout HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:25] \"\u001b[37mGET /_dash-dependencies HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:27] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:27] \"\u001b[37mGET /_dash-component-suites/dash_core_components/async-dropdown.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:27] \"\u001b[37mGET /_dash-component-suites/dash_core_components/async-datepicker.js HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 2447, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1952, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1821, in handle_user_exception\n",
      "    reraise(exc_type, exc_value, tb)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\_compat.py\", line 39, in reraise\n",
      "    raise value\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1950, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\flask\\app.py\", line 1936, in dispatch_request\n",
      "    return self.view_functions[rule.endpoint](**req.view_args)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1096, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\dash.py\", line 1027, in add_context\n",
      "    _validate.validate_multi_return(output_spec, output_value, callback_id)\n",
      "  File \"C:\\Users\\mahav\\Anaconda3\\lib\\site-packages\\dash\\_validate.py\", line 136, in validate_multi_return\n",
      "    raise exceptions.InvalidCallbackReturnValue(\n",
      "dash.exceptions.InvalidCallbackReturnValue: The callback ..tabs.value...model.children.. is a multi-output.\n",
      "Expected the output type to be a list or tuple but got:\n",
      "None.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Aug/2021 14:49:27] \"\u001b[35m\u001b[1mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 500 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1991-01-19\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [15/Aug/2021 14:49:49] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:49] \"\u001b[37mGET /_dash-component-suites/dash_core_components/async-graph.js HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:49] \"\u001b[37mPOST /_dash-update-component HTTP/1.1\u001b[0m\" 200 -\n",
      "127.0.0.1 - - [15/Aug/2021 14:49:49] \"\u001b[37mGET /_dash-component-suites/dash_core_components/async-plotlyjs.js HTTP/1.1\u001b[0m\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "          Date  Observedpr         Modelpr\n",
      "0   1991-01-19        0.00  0.000000508313\n",
      "1   1991-01-20       99.99  0.000002292287\n",
      "2   1991-01-21       99.99  0.000001377609\n",
      "3   1991-01-22        0.00  0.000000000000\n",
      "4   1991-01-23       99.99  0.000000313581\n",
      "..         ...         ...             ...\n",
      "171 1991-07-09        0.00  0.000000072153\n",
      "172 1991-07-10       99.99  0.000000000000\n",
      "173 1991-07-11        0.00  0.000000010444\n",
      "174 1991-07-12        0.00  0.000000064574\n",
      "175 1991-07-13       99.99  0.000000013465\n",
      "\n",
      "[176 rows x 3 columns]\n"
     ]
    }
   ],
   "source": [
    "app = dash.Dash()\n",
    "\n",
    "#df = pd.read_csv(user_key['csv_loc_raw']+'/tas/tas_comparison_output_1991-1995.csv')\n",
    "\n",
    "\n",
    "colors = {\n",
    "    'background': '#fcd8bb',\n",
    "    'text': '#111111'\n",
    "}\n",
    "app.layout = html.Div(style={'backgroundColor': colors['background']}, children=[\n",
    "    html.H1(\n",
    "        children='Model Data Comparison Dashboard',\n",
    "        style={\n",
    "            'textAlign': 'center',\n",
    "            'color': colors['text']\n",
    "        }\n",
    "    ),dcc.Tabs(id='tabs', value='tabs-1', children=[\n",
    "        dcc.Tab(id=\"select\",label='Select Data', value='selectData'),\n",
    "        dcc.Tab(id=\"model\",label='Projected VS Observed', value='projVobs',disabled=True),\n",
    "        dcc.Tab(id=\"ext\",label='Extreme Climate', value='ext',disabled=True),\n",
    "        dcc.Tab(id=\"help\",label='How to use', value='howto'),\n",
    "    ]),\n",
    "    html.Div(id='tabs-content')\n",
    "   \n",
    "])\n",
    "\n",
    "@app.callback(Output('tabs-content', 'children'),\n",
    "              Input('tabs', 'value'))\n",
    "def render_content(tab):\n",
    "    if tab == 'selectData':\n",
    "        return html.Div([\n",
    "            dcc.RadioItems(id='radio-input',\n",
    "            options=[\n",
    "                {'label': 'Project VS Observed', 'value': 'PVSO'},\n",
    "                {'label': 'Extreme Climate Events', 'value': 'Ext'}\n",
    "            ]),\n",
    "            dcc.Dropdown(\n",
    "                    id='region',\n",
    "                    options=[\n",
    "                        {'label': 'Toronto,Canada', 'value': 'TOR'}                       \n",
    "            ]),\n",
    "            dcc.DatePickerRange(\n",
    "                id='date-picker-range',\n",
    "                min_date_allowed=dt.datetime(1991, 1, 1),\n",
    "                max_date_allowed=dt.datetime(1995, 12, 31)\n",
    "\n",
    "            ),\n",
    "            dcc.Dropdown(\n",
    "                    id='variable',\n",
    "                    options=[\n",
    "                        {'label': 'Precipitation', 'value': 'pr'},\n",
    "                        {'label': 'Pressure', 'value': 'ps'},\n",
    "                        {'label': 'Surface Radiation', 'value': 'rsds'},\n",
    "                        {'label': 'Surface Temperature', 'value': 'tas'},\n",
    "                        {'label': 'Surface Wind Speed', 'value': 'sfcWind'}\n",
    "            ]),\n",
    "            html.Button('Submit', id='submit-val', n_clicks=0)\n",
    "            \n",
    "        ])\n",
    "               \n",
    "\n",
    "    elif tab == 'howto':\n",
    "        return html.Div([\n",
    "            html.H3('How to use this tool:'),\n",
    "            html.H5('1. In the Select Data tab, select the type of analyis, region, date range, and variable'),\n",
    "            html.H5('2. Review the data output in the appropriate tab')\n",
    "        ])\n",
    "    elif tab == 'projVobs':\n",
    "        return html.Div([\n",
    "            html.H3('Projected vs Observed:'),\n",
    "            dcc.Graph(id='graph')\n",
    "        ])\n",
    "    elif tab == 'ext':\n",
    "        return html.Div([\n",
    "            html.H3('Extreme Climate:')\n",
    "        ])\n",
    "\n",
    "\n",
    "\n",
    "    \n",
    "@app.callback(\n",
    "    Output(\"tabs\", \"value\"),\n",
    "    Output(\"model\", \"children\"),\n",
    "    [Input(\"submit-val\", \"n_clicks\")],\n",
    "    state=[State(component_id='region', component_property='value'), State('variable', 'value'), State('radio-input', 'value'),State('date-picker-range', 'start_date'),State('date-picker-range', 'end_date')])\n",
    "def tab_resources(click,region,variable,typeof,startDatePicked,endDatePicked):\n",
    "    if click:\n",
    "        \n",
    "        #this is where we calculate stuff\n",
    "        #Insert Inputs HERE\n",
    "\n",
    "        #lat and long are currently not relevant\n",
    "\n",
    "        #date range (change to read user input)\n",
    "        print(startDatePicked)\n",
    "        startDate = dt.datetime.strptime(startDatePicked,'%Y-%m-%d')\n",
    " \n",
    "        endDate = dt.datetime.strptime(endDatePicked,'%Y-%m-%d')\n",
    "\n",
    "\n",
    "        #variable (change to read user input)\n",
    "        variable = variable\n",
    "\n",
    "        \n",
    "        data=pd.read_csv(user_key['csv_loc_raw']+'/'+variable+'/'+variable+'_converted_output_1991-1995.csv')\n",
    "\n",
    "        if variable =='rsds':\n",
    "            observeData=pd.read_excel(user_key['GSOD_Loc']+'WRDC.xlsx',sheet_name=2)\n",
    "        else:\n",
    "            observeData=pd.read_excel(user_key['GSOD_Loc']+'GSOD.xlsx',sheet_name=2)\n",
    "        \n",
    "        \n",
    "        data['Date'] =  pd.to_datetime(data['Date'], format='%Y-%m-%d')\n",
    "        \n",
    "        if variable == 'tas':\n",
    "            #then it is TEMP in the data, find the column\n",
    "            column = 'TEMP'\n",
    "        elif variable == 'pr' :\n",
    "            column = 'PRCP'\n",
    "            \n",
    "        elif variable == 'ps' :\n",
    "            column = 'STP'\n",
    "            \n",
    "        elif variable == 'sfcWind' :\n",
    "            column = 'WDSP'\n",
    "          \n",
    "\n",
    "        #with the date range\n",
    "        row_iterator = observeData.iterrows()\n",
    "        counter =0\n",
    "\n",
    "        dates = []\n",
    "        observedData = []\n",
    "        modelData = []\n",
    "\n",
    "        #the for loop will loop through the observed data file (GSOD)\n",
    "        for i, row in row_iterator:\n",
    "                if counter != len(observeData):\n",
    "                    #if the date is within the specified range\n",
    "                    if observeData.at[i,'DATE'] >= startDate and observeData.at[i,'DATE'] <= endDate:\n",
    "                        #here we add the date and temp (Farenheit) to the lists\n",
    "                        dates.append(observeData.at[i,'DATE'])\n",
    "                        observedData.append(observeData.at[i,column])\n",
    "                counter += 1\n",
    "\n",
    "        row_ittr2 = data.iterrows()\n",
    "        counter =0\n",
    "        #the for loop will loop through the model data file \n",
    "        for i, row in row_ittr2:\n",
    "                if counter != len(data):\n",
    "                    #if the date is within the specified range\n",
    "                    if data.at[i,'Date'] >= startDate and data.at[i,'Date'] <= endDate:\n",
    "                        #here we add the temp (Farenheit) to the lists\n",
    "                        modelData.append(data.at[i,'Variable_converted'])\n",
    "                counter += 1\n",
    "\n",
    "\n",
    "\n",
    "        #now we have all the variables in array now we create a dataframe\n",
    "        data_all = pd.DataFrame()\n",
    "        data_all.insert(0, 'Date', dates)\n",
    "        data_all.insert(1, 'Observed'+variable, observedData)\n",
    "        data_all.insert(2, 'Model'+variable, modelData)\n",
    "        \n",
    "        print(data_all)\n",
    "        \n",
    "        fig = make_subplots(rows=2, cols=1, shared_xaxes=True)\n",
    "        \n",
    "        fig.add_trace(go.Scatter(x=data_all['Date'], y=data_all['Observed'+variable]))\n",
    "        fig.add_trace(go.Scatter(x=data_all['Date'], y=data_all['Model'+variable]))\n",
    "\n",
    "\n",
    "        \n",
    "        graph = html.Div([\n",
    "            \n",
    "\n",
    "            (dcc.Graph(\n",
    "               id='Graph1',\n",
    "               figure=fig\n",
    "           )) \n",
    "        \n",
    "        ])\n",
    "\n",
    "        \n",
    "        \n",
    "        if typeof == 'PVSO':\n",
    "            return 'projVobs',graph\n",
    "        else:\n",
    "            return 'ext'         \n",
    " \n",
    "\n",
    " \n",
    "if __name__ == '__main__':\n",
    "    app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    " #dcc.Graph(\n",
    "  #      id='Graph1',\n",
    "  #      figure={\n",
    "  #          'data': [\n",
    "   #             {'x': df['Date'], 'y': df['Observedtas'], 'type': 'bar', 'name': 'Observed TAS'},\n",
    "   #             {'x': df['Date'], 'y': df['Modeltas'], 'type': 'bar', 'name': 'Model TAS'},\n",
    "   #         ],\n",
    "   #         'layout': {\n",
    "   #             'plot_bgcolor': colors['background'],\n",
    "   #             'paper_bgcolor': colors['background'],\n",
    "   #             'font': {\n",
    "   #                 'color': colors['text']\n",
    "   #             }\n",
    "   #         }\n",
    "  #      }\n",
    "   # )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
